### ISSUE TITLE
Missing modal-body in modal example

### ISSUE THREAD

**Issue by giannik** [NevitFeridi/AJAX-TagHelper-For-ASP.NET-Core-MVC#1]
Hi. 
In the modal example I think there is a missing div with modal-body class , because it does'nt work without it. 

Here is how it should be :
```
<!-- Modal -->
<div class="modal fade" id="exampleModalScrollable" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable" role="document">
        <div class="modal-content" id="modalContent2">
			<div class="modal-body">
                               
             </div>
        </div>
    </div>
</div>
```

**Comment by NevitFeridi** [comment]
Hi Dear
the div with modal-body class should be in the view which refer to action used in asp-action attribute

Please see the subject in the sample provided
/views/home/modaltest.cshtml
